export const STRIPE_SUPPORTED_COUNTRIES = [
  { code: 'US', name: 'États-Unis' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'GB', name: 'Royaume-Uni' },
  { code: 'ES', name: 'Espagne' },
  { code: 'IT', name: 'Italie' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australie' },
  { code: 'BE', name: 'Belgique' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'SE', name: 'Suède' },
  { code: 'CH', name: 'Suisse' },
  { code: 'FI', name: 'Finlande' },
  { code: 'IE', name: 'Irlande' },
  { code: 'DK', name: 'Danemark' },
  { code: 'NO', name: 'Norvège' },
  { code: 'PT', name: 'Portugal' },
  { code: 'AT', name: 'Autriche' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'SG', name: 'Singapour' },
  { code: 'NZ', name: 'Nouvelle-Zélande' },
  { code: 'PL', name: 'Pologne' },
  { code: 'CZ', name: 'République tchèque' },
  { code: 'GR', name: 'Grèce' },
  { code: 'RO', name: 'Roumanie' },
];
